insert into config_keys (key, description, data_type, is_public) values
  ('auth.emailLabel', 'Label for email input', 'string', true),
  ('auth.passwordLabel', 'Label for password input', 'string', true),
  ('auth.currentPasswordLabel', 'Label for current password input', 'string', true),
  ('auth.newPasswordLabel', 'Label for new password input', 'string', true),
  ('auth.signInButton', 'Sign in button text', 'string', true),
  ('auth.signUpButton', 'Sign up button text', 'string', true),
  ('auth.creatingAccount', 'Creating account loading text', 'string', true),
  ('auth.signingIn', 'Signing in loading text', 'string', true),
  ('auth.noAccountPrompt', 'Prompt for users without an account', 'string', true),
  ('auth.createOneLink', 'Link text to create an account', 'string', true),
  ('auth.alreadyHaveAccountPrompt', 'Prompt for users who already have an account', 'string', true),
  ('auth.signInLink', 'Link text to sign in', 'string', true),

  ('ui.today', 'Today label', 'string', true),
  ('ui.showCompleted', 'Toggle label for showing completed tasks', 'string', true),
  ('ui.itemsCount', 'Label for item count', 'string', true),
  ('ui.noTasksFound', 'Message when no tasks are found', 'string', true),
  ('ui.projectEmptyStateText', 'Message when a project is empty', 'string', true),
  ('ui.searchPlaceholder', 'Placeholder for search input', 'string', true),
  ('ui.loading', 'Generic loading text', 'string', true),
  ('ui.errorPrefix', 'Generic error prefix', 'string', true),
  ('ui.saveChanges', 'Save changes button text', 'string', true),
  ('ui.reset', 'Reset button text', 'string', true),
  ('ui.saving', 'Saving loading text', 'string', true),
  ('ui.actions', 'Actions label', 'string', true),
  ('ui.cancel', 'Cancel button text', 'string', true),
  ('ui.confirm', 'Confirm button text', 'string', true),
  ('ui.active', 'Active status label', 'string', true),
  ('ui.inactive', 'Inactive status label', 'string', true),
  ('ui.status', 'Status label', 'string', true),
  ('ui.role', 'Role label', 'string', true),
  ('ui.lastLogin', 'Last login label', 'string', true),
  ('ui.neverLoggedIn', 'Never logged in label', 'string', true),
  ('ui.id', 'ID label', 'string', true),
  ('ui.email', 'Email label', 'string', true),
  ('ui.allRoles', 'Filter option: all roles', 'string', true),
  ('ui.adminsOnly', 'Filter option: admins only', 'string', true),
  ('ui.usersOnly', 'Filter option: users only', 'string', true),
  ('ui.allStatus', 'Filter option: all status', 'string', true),
  ('ui.changeUserStatus', 'Button text to change user status', 'string', true),
  ('ui.you', 'Label for the current user', 'string', true),
  ('ui.adminRole', 'Admin role name', 'string', true),
  ('ui.userRole', 'User role name', 'string', true),
  ('ui.never', 'Never label', 'string', true),
  ('ui.systemStatus', 'System status header', 'string', true),
  ('ui.systemInformation', 'System information header', 'string', true),
  ('ui.backendHealth', 'Backend health label', 'string', true),
  ('ui.dbReady', 'DB ready label', 'string', true),
  ('ui.webVersion', 'Web version label', 'string', true),
  ('ui.backendVersion', 'Backend version label', 'string', true),
  ('ui.totalUsers', 'Total users count label', 'string', true),
  ('ui.databaseMetrics', 'Database metrics header', 'string', true),
  ('ui.databaseSize', 'Database size label', 'string', true),
  ('ui.activeConnections', 'Active connections label', 'string', true),
  ('ui.cacheHitRatio', 'Cache hit ratio label', 'string', true),
  ('ui.deadlocks', 'Deadlocks count label', 'string', true),
  ('ui.blocksRead', 'Blocks read count label', 'string', true),
  ('ui.blocksHit', 'Blocks hit count label', 'string', true),
  ('ui.passwordSecurity', 'Password security header', 'string', true),
  ('ui.atLeast8Chars', 'Requirement: at least 8 characters', 'string', true),
  ('ui.uppercaseLetter', 'Requirement: uppercase letter', 'string', true),
  ('ui.lowercaseLetter', 'Requirement: lowercase letter', 'string', true),
  ('ui.numberRequirement', 'Requirement: number', 'string', true),
  ('ui.specialCharRequirement', 'Requirement: special character', 'string', true),
  ('ui.appTheme', 'App theme setting label', 'string', true),
  ('ui.themeDescription', 'App theme setting description', 'string', true),
  ('ui.completedTasks', 'Completed tasks setting label', 'string', true),
  ('ui.completedTasksDescription', 'Completed tasks setting description', 'string', true),
  ('ui.language', 'Language setting label', 'string', true),
  ('ui.languageDescription', 'Language setting description', 'string', true),
  ('ui.account', 'Account section label', 'string', true),
  ('ui.preferences', 'Preferences section label', 'string', true),
  ('ui.security', 'Security section label', 'string', true),
  ('ui.edit', 'Edit button text', 'string', true),
  ('ui.save', 'Save button text', 'string', true),
  ('ui.settingsTitle', 'Settings page title', 'string', true),
  ('ui.settingsSubtitle', 'Settings page subtitle', 'string', true),

  ('navigation.userData', 'Nav label: user data', 'string', true)
on conflict (key) do nothing;

-- en translations
insert into config_translations (key, language_code, value) values
  ('auth.emailLabel', 'en', 'Email Address'),
  ('auth.passwordLabel', 'en', 'Password'),
  ('auth.currentPasswordLabel', 'en', 'Current Password'),
  ('auth.newPasswordLabel', 'en', 'New Password'),
  ('auth.signInButton', 'en', 'Sign in'),
  ('auth.signUpButton', 'en', 'Create account'),
  ('auth.creatingAccount', 'en', 'Creating account...'),
  ('auth.signingIn', 'en', 'Signing in...'),
  ('auth.noAccountPrompt', 'en', 'Don''t have an account?'),
  ('auth.createOneLink', 'en', 'Create one'),
  ('auth.alreadyHaveAccountPrompt', 'en', 'Already have an account?'),
  ('auth.signInLink', 'en', 'Sign in'),
  ('ui.today', 'en', 'Today'),
  ('ui.showCompleted', 'en', 'Show completed'),
  ('ui.itemsCount', 'en', 'items'),
  ('ui.noTasksFound', 'en', 'No tasks found'),
  ('ui.projectEmptyStateText', 'en', 'This project is currently empty. Start by adding a task.'),
  ('ui.searchPlaceholder', 'en', 'Search...'),
  ('ui.loading', 'en', 'Loading...'),
  ('ui.errorPrefix', 'en', 'Error'),
  ('ui.saveChanges', 'en', 'Save Changes'),
  ('ui.reset', 'en', 'Reset'),
  ('ui.saving', 'en', 'Saving...'),
  ('ui.actions', 'en', 'Actions'),
  ('ui.cancel', 'en', 'Cancel'),
  ('ui.confirm', 'en', 'Confirm'),
  ('ui.active', 'en', 'Active'),
  ('ui.inactive', 'en', 'Inactive'),
  ('ui.status', 'en', 'Status'),
  ('ui.role', 'en', 'Role'),
  ('ui.lastLogin', 'en', 'Last Login'),
  ('ui.neverLoggedIn', 'en', 'Never logged in'),
  ('ui.id', 'en', 'ID'),
  ('ui.email', 'en', 'Email'),
  ('ui.allRoles', 'en', 'All Roles'),
  ('ui.adminsOnly', 'en', 'Admins Only'),
  ('ui.usersOnly', 'en', 'Users Only'),
  ('ui.allStatus', 'en', 'All Status'),
  ('ui.changeUserStatus', 'en', 'Change User Status'),
  ('ui.you', 'en', 'You'),
  ('ui.adminRole', 'en', 'Admin'),
  ('ui.userRole', 'en', 'User'),
  ('ui.never', 'en', 'Never'),
  ('ui.systemStatus', 'en', 'System Status'),
  ('ui.systemInformation', 'en', 'System Information'),
  ('ui.backendHealth', 'en', 'Backend Health'),
  ('ui.dbReady', 'en', 'DB Ready'),
  ('ui.webVersion', 'en', 'Web Version'),
  ('ui.backendVersion', 'en', 'Backend Version'),
  ('ui.totalUsers', 'en', 'Total Users'),
  ('ui.databaseMetrics', 'en', 'Database Metrics'),
  ('ui.databaseSize', 'en', 'Database Size'),
  ('ui.activeConnections', 'en', 'Active Connections'),
  ('ui.cacheHitRatio', 'en', 'Cache Hit Ratio'),
  ('ui.deadlocks', 'en', 'Deadlocks'),
  ('ui.blocksRead', 'en', 'Blocks Read'),
  ('ui.blocksHit', 'en', 'Blocks Hit'),
  ('ui.passwordSecurity', 'en', 'Password Security'),
  ('ui.atLeast8Chars', 'en', 'At least 8 characters'),
  ('ui.uppercaseLetter', 'en', 'Uppercase letter'),
  ('ui.lowercaseLetter', 'en', 'Lowercase letter'),
  ('ui.numberRequirement', 'en', 'Number'),
  ('ui.specialCharRequirement', 'en', 'Special character'),
  ('ui.appTheme', 'en', 'App Theme'),
  ('ui.themeDescription', 'en', 'Personalize your workspace with a theme that fits your flow.'),
  ('ui.completedTasks', 'en', 'Completed Tasks'),
  ('ui.completedTasksDescription', 'en', 'Automatically show completed tasks in your projects by default.'),
  ('ui.language', 'en', 'Language'),
  ('ui.languageDescription', 'en', 'Choose your preferred language for the interface.'),
  ('ui.account', 'en', 'Account'),
  ('ui.preferences', 'en', 'Preferences'),
  ('ui.security', 'en', 'Security'),
  ('ui.edit', 'en', 'Edit'),
  ('ui.save', 'en', 'Save'),
  ('ui.settingsTitle', 'en', 'Settings'),
  ('ui.settingsSubtitle', 'en', 'Manage your workspace and security.'),
  ('navigation.userData', 'en', 'User Data')
on conflict (key, language_code) do update set value = excluded.value;

-- fr translations
insert into config_translations (key, language_code, value) values
  ('auth.emailLabel', 'fr', 'Adresse e-mail'),
  ('auth.passwordLabel', 'fr', 'Mot de passe'),
  ('auth.currentPasswordLabel', 'fr', 'Mot de passe actuel'),
  ('auth.newPasswordLabel', 'fr', 'Nouveau mot de passe'),
  ('auth.signInButton', 'fr', 'Se connecter'),
  ('auth.signUpButton', 'fr', 'Créer un compte'),
  ('auth.creatingAccount', 'fr', 'Création du compte...'),
  ('auth.signingIn', 'fr', 'Connexion...'),
  ('auth.noAccountPrompt', 'fr', 'Vous n''avez pas de compte ?'),
  ('auth.createOneLink', 'fr', 'En créer un'),
  ('auth.alreadyHaveAccountPrompt', 'fr', 'Vous avez déjà un compte ?'),
  ('auth.signInLink', 'fr', 'Se connecter'),
  ('ui.today', 'fr', 'Aujourd''hui'),
  ('ui.showCompleted', 'fr', 'Afficher les tâches terminées'),
  ('ui.itemsCount', 'fr', 'éléments'),
  ('ui.noTasksFound', 'fr', 'Aucune tâche trouvée'),
  ('ui.projectEmptyStateText', 'fr', 'Ce projet est actuellement vide. Commencez par ajouter une tâche.'),
  ('ui.searchPlaceholder', 'fr', 'Rechercher...'),
  ('ui.loading', 'fr', 'Chargement...'),
  ('ui.errorPrefix', 'fr', 'Erreur'),
  ('ui.saveChanges', 'fr', 'Enregistrer les modifications'),
  ('ui.reset', 'fr', 'Réinitialiser'),
  ('ui.saving', 'fr', 'Enregistrement...'),
  ('ui.actions', 'fr', 'Actions'),
  ('ui.cancel', 'fr', 'Annuler'),
  ('ui.confirm', 'fr', 'Confirmer'),
  ('ui.active', 'fr', 'Actif'),
  ('ui.inactive', 'fr', 'Inactif'),
  ('ui.status', 'fr', 'Statut'),
  ('ui.role', 'fr', 'Rôle'),
  ('ui.lastLogin', 'fr', 'Dernière connexion'),
  ('ui.neverLoggedIn', 'fr', 'Jamais connecté'),
  ('ui.id', 'fr', 'ID'),
  ('ui.email', 'fr', 'E-mail'),
  ('ui.allRoles', 'fr', 'Tous les rôles'),
  ('ui.adminsOnly', 'fr', 'Administrateurs uniquement'),
  ('ui.usersOnly', 'fr', 'Utilisateurs uniquement'),
  ('ui.allStatus', 'fr', 'Tous les statuts'),
  ('ui.changeUserStatus', 'fr', 'Changer le statut de l''utilisateur'),
  ('ui.you', 'fr', 'Vous'),
  ('ui.adminRole', 'fr', 'Administrateur'),
  ('ui.userRole', 'fr', 'Utilisateur'),
  ('ui.never', 'fr', 'Jamais'),
  ('ui.systemStatus', 'fr', 'Statut du système'),
  ('ui.systemInformation', 'fr', 'Informations système'),
  ('ui.backendHealth', 'fr', 'Santé du backend'),
  ('ui.dbReady', 'fr', 'Base de données prête'),
  ('ui.webVersion', 'fr', 'Version Web'),
  ('ui.backendVersion', 'fr', 'Version du Backend'),
  ('ui.totalUsers', 'fr', 'Nombre total d''utilisateurs'),
  ('ui.databaseMetrics', 'fr', 'Métriques de la base de données'),
  ('ui.databaseSize', 'fr', 'Taille de la base de données'),
  ('ui.activeConnections', 'fr', 'Connexions actives'),
  ('ui.cacheHitRatio', 'fr', 'Taux de réussite du cache'),
  ('ui.deadlocks', 'fr', 'Interblocages'),
  ('ui.blocksRead', 'fr', 'Blocs lus'),
  ('ui.blocksHit', 'fr', 'Blocs trouvés dans le cache'),
  ('ui.passwordSecurity', 'fr', 'Sécurité du mot de passe'),
  ('ui.atLeast8Chars', 'fr', 'Au moins 8 caractères'),
  ('ui.uppercaseLetter', 'fr', 'Lettre majuscule'),
  ('ui.lowercaseLetter', 'fr', 'Lettre minuscule'),
  ('ui.numberRequirement', 'fr', 'Chiffre'),
  ('ui.specialCharRequirement', 'fr', 'Caractère spécial'),
  ('ui.appTheme', 'fr', 'Thème de l''application'),
  ('ui.themeDescription', 'fr', 'Personnalisez votre espace de travail avec un thème qui correspond à votre flux.'),
  ('ui.completedTasks', 'fr', 'Tâches terminées'),
  ('ui.completedTasksDescription', 'fr', 'Afficher automatiquement les tâches terminées dans vos projets par défaut.'),
  ('ui.language', 'fr', 'Langue'),
  ('ui.languageDescription', 'fr', 'Choisissez votre langue préférée pour l''interface.'),
  ('ui.account', 'fr', 'Compte'),
  ('ui.preferences', 'fr', 'Préférences'),
  ('ui.security', 'fr', 'Sécurité'),
  ('ui.edit', 'fr', 'Modifier'),
  ('ui.save', 'fr', 'Enregistrer'),
  ('ui.settingsTitle', 'fr', 'Paramètres'),
  ('ui.settingsSubtitle', 'fr', 'Gérez votre espace de travail et votre sécurité.'),
  ('navigation.userData', 'fr', 'Données utilisateur')
on conflict (key, language_code) do update set value = excluded.value;

-- de translations
insert into config_translations (key, language_code, value) values
  ('auth.emailLabel', 'de', 'E-Mail-Adresse'),
  ('auth.passwordLabel', 'de', 'Passwort'),
  ('auth.currentPasswordLabel', 'de', 'Aktuelles Passwort'),
  ('auth.newPasswordLabel', 'de', 'Neues Passwort'),
  ('auth.signInButton', 'de', 'Anmelden'),
  ('auth.signUpButton', 'de', 'Konto erstellen'),
  ('auth.creatingAccount', 'de', 'Konto wird erstellt...'),
  ('auth.signingIn', 'de', 'Anmeldung...'),
  ('auth.noAccountPrompt', 'de', 'Haben Sie noch kein Konto?'),
  ('auth.createOneLink', 'de', 'Eines erstellen'),
  ('auth.alreadyHaveAccountPrompt', 'de', 'Haben Sie bereits ein Konto?'),
  ('auth.signInLink', 'de', 'Anmelden'),
  ('ui.today', 'de', 'Heute'),
  ('ui.showCompleted', 'de', 'Erledigte anzeigen'),
  ('ui.itemsCount', 'de', 'Elemente'),
  ('ui.noTasksFound', 'de', 'Keine Aufgaben gefunden'),
  ('ui.projectEmptyStateText', 'de', 'Dieses Projekt ist derzeit leer. Beginnen Sie mit dem Hinzufügen einer Aufgabe.'),
  ('ui.searchPlaceholder', 'de', 'Suchen...'),
  ('ui.loading', 'de', 'Laden...'),
  ('ui.errorPrefix', 'de', 'Fehler'),
  ('ui.saveChanges', 'de', 'Änderungen speichern'),
  ('ui.reset', 'de', 'Zurücksetzen'),
  ('ui.saving', 'de', 'Speichern...'),
  ('ui.actions', 'de', 'Aktionen'),
  ('ui.cancel', 'de', 'Abbrechen'),
  ('ui.confirm', 'de', 'Bestätigen'),
  ('ui.active', 'de', 'Aktiv'),
  ('ui.inactive', 'de', 'Inaktiv'),
  ('ui.status', 'de', 'Status'),
  ('ui.role', 'de', 'Rolle'),
  ('ui.lastLogin', 'de', 'Letzter Login'),
  ('ui.neverLoggedIn', 'de', 'Nie angemeldet'),
  ('ui.id', 'de', 'ID'),
  ('ui.email', 'de', 'E-Mail'),
  ('ui.allRoles', 'de', 'Alle Rollen'),
  ('ui.adminsOnly', 'de', 'Nur Admins'),
  ('ui.usersOnly', 'de', 'Nur Benutzer'),
  ('ui.allStatus', 'de', 'Alle Status'),
  ('ui.changeUserStatus', 'de', 'Benutzerstatus ändern'),
  ('ui.you', 'de', 'Sie'),
  ('ui.adminRole', 'de', 'Admin'),
  ('ui.userRole', 'de', 'Benutzer'),
  ('ui.never', 'de', 'Nie'),
  ('ui.systemStatus', 'de', 'Systemstatus'),
  ('ui.systemInformation', 'de', 'Systeminformationen'),
  ('ui.backendHealth', 'de', 'Backend-Status'),
  ('ui.dbReady', 'de', 'DB bereit'),
  ('ui.webVersion', 'de', 'Web-Version'),
  ('ui.backendVersion', 'de', 'Backend-Version'),
  ('ui.totalUsers', 'de', 'Benutzer gesamt'),
  ('ui.databaseMetrics', 'de', 'Datenbank-Metriken'),
  ('ui.databaseSize', 'de', 'Datenbankgröße'),
  ('ui.activeConnections', 'de', 'Aktive Verbindungen'),
  ('ui.cacheHitRatio', 'de', 'Cache-Trefferquote'),
  ('ui.deadlocks', 'de', 'Deadlocks'),
  ('ui.blocksRead', 'de', 'Gelesene Blöcke'),
  ('ui.blocksHit', 'de', 'Block-Hits'),
  ('ui.passwordSecurity', 'de', 'Passwortsicherheit'),
  ('ui.atLeast8Chars', 'de', 'Mindestens 8 Zeichen'),
  ('ui.uppercaseLetter', 'de', 'Großbuchstabe'),
  ('ui.lowercaseLetter', 'de', 'Kleinbuchstabe'),
  ('ui.numberRequirement', 'de', 'Zahl'),
  ('ui.specialCharRequirement', 'de', 'Sonderzeichen'),
  ('ui.appTheme', 'de', 'App-Design'),
  ('ui.themeDescription', 'de', 'Personalisieren Sie Ihren Arbeitsbereich mit einem Design, das zu Ihrem Flow passt.'),
  ('ui.completedTasks', 'de', 'Erledigte Aufgaben'),
  ('ui.completedTasksDescription', 'de', 'Erledigte Aufgaben in Ihren Projekten standardmäßig automatisch anzeigen.'),
  ('ui.language', 'de', 'Sprache'),
  ('ui.languageDescription', 'de', 'Wählen Sie Ihre bevorzugte Sprache für die Benutzeroberfläche.'),
  ('ui.account', 'de', 'Konto'),
  ('ui.preferences', 'de', 'Einstellungen'),
  ('ui.security', 'de', 'Sicherheit'),
  ('ui.edit', 'de', 'Bearbeiten'),
  ('ui.save', 'de', 'Speichern'),
  ('ui.settingsTitle', 'de', 'Einstellungen'),
  ('ui.settingsSubtitle', 'de', 'Verwalten Sie Ihren Arbeitsbereich und Ihre Sicherheit.'),
  ('navigation.userData', 'de', 'Benutzerdaten')
on conflict (key, language_code) do update set value = excluded.value;
