insert into config_keys (key, description, data_type, is_public) values
  ('ui.noDueDate', 'Label for tasks with no due date', 'string', true),
  ('ui.recurringTemplate', 'Label for recurring task templates', 'string', true),
  ('ui.everyMonth', 'Label for monthly recurrence', 'string', true),
  ('ui.occurrences', 'Label for task occurrences', 'string', true),
  ('ui.createProjectTitle', 'Title for create project dialog', 'string', true),
  ('ui.createProjectSubtitle', 'Subtitle for create project dialog', 'string', true),
  ('ui.projectNameLabel', 'Label for project name input', 'string', true),
  ('ui.projectNamePlaceholder', 'Placeholder for project name input', 'string', true),
  ('ui.projectDescriptionLabel', 'Label for project description input', 'string', true),
  ('ui.projectDescriptionPlaceholder', 'Placeholder for project description input', 'string', true),
  ('ui.createProjectButton', 'Button text to create project', 'string', true),
  ('ui.editProjectTitle', 'Title for edit project dialog', 'string', true),
  ('ui.editProjectSubtitle', 'Subtitle for edit project dialog', 'string', true),
  ('ui.saveChangesButton', 'Button text to save changes', 'string', true),
  ('ui.deleteProjectButton', 'Button text to delete project', 'string', true),
  ('ui.deleteProjectConfirm', 'Confirmation message for deleting a project', 'string', true),
  ('ui.createTaskTitle', 'Title for create task dialog', 'string', true),
  ('ui.editTaskTitle', 'Title for edit task dialog', 'string', true),
  ('ui.taskTitleLabel', 'Label for task title input', 'string', true),
  ('ui.taskTitlePlaceholder', 'Placeholder for task title input', 'string', true),
  ('ui.taskDescriptionLabel', 'Label for task description input', 'string', true),
  ('ui.taskDescriptionPlaceholder', 'Placeholder for task description input', 'string', true),
  ('ui.dueDateLabel', 'Label for due date input', 'string', true),
  ('ui.tagsLabel', 'Label for tags selection', 'string', true),
  ('ui.addTagPlaceholder', 'Placeholder for adding a tag', 'string', true),
  ('ui.addButton', 'General Add button text', 'string', true),
  ('ui.repeatEveryLabel', 'Label for recurrence interval', 'string', true),
  ('ui.frequencyLabel', 'Label for recurrence frequency', 'string', true),
  ('ui.dayUnit', 'Day unit label', 'string', true),
  ('ui.weekUnit', 'Week unit label', 'string', true),
  ('ui.monthUnit', 'Month unit label', 'string', true),
  ('ui.recurringLabel', 'Label for recurring status', 'string', true),
  ('ui.createTaskButton', 'Button text to create task', 'string', true),
  ('ui.deleteTaskButton', 'Button text to delete task', 'string', true),
  ('ui.manageTagsTitle', 'Title for manage tags page', 'string', true),
  ('ui.manageTagsSubtitle', 'Subtitle for manage tags page', 'string', true),
  ('ui.createNewTagPlaceholder', 'Placeholder for create tag input', 'string', true),
  ('ui.createButton', 'General Create button text', 'string', true),
  ('ui.noTagsYet', 'Message when no tags exist', 'string', true),
  ('ui.editTagTitle', 'Title for edit tag dialog', 'string', true),
  ('ui.deleteTagTitle', 'Title for delete tag dialog', 'string', true),
  ('ui.loadingProjectDetails', 'Loading text for project details', 'string', true),
  ('ui.loadingTags', 'Loading text for tags', 'string', true),
  ('ui.taskTitleRequired', 'Validation error: task title required', 'string', true),
  ('ui.dueDateRequiredForRecurring', 'Validation error: due date required for recurring task', 'string', true),
  ('ui.projectNameRequired', 'Validation error: project name required', 'string', true)
on conflict (key) do nothing;

-- en translations
insert into config_translations (key, language_code, value) values
  ('ui.noDueDate', 'en', 'No due date'),
  ('ui.recurringTemplate', 'en', 'Recurring Template'),
  ('ui.everyMonth', 'en', 'Every 1 month'),
  ('ui.occurrences', 'en', 'Occurrences'),
  ('ui.createProjectTitle', 'en', 'Create New Project'),
  ('ui.createProjectSubtitle', 'en', 'Start something new'),
  ('ui.projectNameLabel', 'en', 'Project Name'),
  ('ui.projectNamePlaceholder', 'en', 'e.g. Personal Website'),
  ('ui.projectDescriptionLabel', 'en', 'Description'),
  ('ui.projectDescriptionPlaceholder', 'en', 'What is this project about?'),
  ('ui.createProjectButton', 'en', 'Create Project'),
  ('ui.editProjectTitle', 'en', 'Edit Project'),
  ('ui.editProjectSubtitle', 'en', 'Workspace Settings'),
  ('ui.saveChangesButton', 'en', 'Save Changes'),
  ('ui.deleteProjectButton', 'en', 'Delete'),
  ('ui.deleteProjectConfirm', 'en', 'Are you sure you want to delete this project? All tasks within will be lost.'),
  ('ui.createTaskTitle', 'en', 'Create Task'),
  ('ui.editTaskTitle', 'en', 'Edit Task'),
  ('ui.taskTitleLabel', 'en', 'Title'),
  ('ui.taskTitlePlaceholder', 'en', 'Task title'),
  ('ui.taskDescriptionLabel', 'en', 'Description'),
  ('ui.taskDescriptionPlaceholder', 'en', 'Add a description...'),
  ('ui.dueDateLabel', 'en', 'Due Date'),
  ('ui.tagsLabel', 'en', 'Tags'),
  ('ui.addTagPlaceholder', 'en', 'Add tag...'),
  ('ui.addButton', 'en', 'Add'),
  ('ui.repeatEveryLabel', 'en', 'Repeat Every'),
  ('ui.frequencyLabel', 'en', 'Frequency'),
  ('ui.dayUnit', 'en', 'Day(s)'),
  ('ui.weekUnit', 'en', 'Week(s)'),
  ('ui.monthUnit', 'en', 'Month(s)'),
  ('ui.recurringLabel', 'en', 'Recurring'),
  ('ui.createTaskButton', 'en', 'Create Task'),
  ('ui.deleteTaskButton', 'en', 'Delete'),
  ('ui.manageTagsTitle', 'en', 'Manage Tags'),
  ('ui.manageTagsSubtitle', 'en', 'Organize your workspace'),
  ('ui.createNewTagPlaceholder', 'en', 'Create new tag...'),
  ('ui.createButton', 'en', 'Create'),
  ('ui.noTagsYet', 'en', 'No tags created yet.'),
  ('ui.editTagTitle', 'en', 'Edit tag'),
  ('ui.deleteTagTitle', 'en', 'Delete tag'),
  ('ui.loadingProjectDetails', 'en', 'Loading project details...'),
  ('ui.loadingTags', 'en', 'Loading tags...'),
  ('ui.taskTitleRequired', 'en', 'Title is required'),
  ('ui.dueDateRequiredForRecurring', 'en', 'Due date is required for recurring tasks'),
  ('ui.projectNameRequired', 'en', 'Project name is required')
on conflict (key, language_code) do update set value = excluded.value;

-- fr translations
insert into config_translations (key, language_code, value) values
  ('ui.noDueDate', 'fr', 'Pas de date d''échéance'),
  ('ui.recurringTemplate', 'fr', 'Modèle récurrent'),
  ('ui.everyMonth', 'fr', 'Tous les 1 mois'),
  ('ui.occurrences', 'fr', 'Occurrences'),
  ('ui.createProjectTitle', 'fr', 'Créer un nouveau projet'),
  ('ui.createProjectSubtitle', 'fr', 'Commencer quelque chose de nouveau'),
  ('ui.projectNameLabel', 'fr', 'Nom du projet'),
  ('ui.projectNamePlaceholder', 'fr', 'ex. Site Web Personnel'),
  ('ui.projectDescriptionLabel', 'fr', 'Description'),
  ('ui.projectDescriptionPlaceholder', 'fr', 'De quoi traite ce projet ?'),
  ('ui.createProjectButton', 'fr', 'Créer le projet'),
  ('ui.editProjectTitle', 'fr', 'Modifier le projet'),
  ('ui.editProjectSubtitle', 'fr', 'Paramètres de l''espace de travail'),
  ('ui.saveChangesButton', 'fr', 'Enregistrer les modifications'),
  ('ui.deleteProjectButton', 'fr', 'Supprimer'),
  ('ui.deleteProjectConfirm', 'fr', 'Êtes-vous sûr de vouloir supprimer ce projet ? Toutes les tâches qu''il contient seront perdues.'),
  ('ui.createTaskTitle', 'fr', 'Créer une tâche'),
  ('ui.editTaskTitle', 'fr', 'Modifier la tâche'),
  ('ui.taskTitleLabel', 'fr', 'Titre'),
  ('ui.taskTitlePlaceholder', 'fr', 'Titre de la tâche'),
  ('ui.taskDescriptionLabel', 'fr', 'Description'),
  ('ui.taskDescriptionPlaceholder', 'fr', 'Ajouter une description...'),
  ('ui.dueDateLabel', 'fr', 'Date d''échéance'),
  ('ui.tagsLabel', 'fr', 'Tags'),
  ('ui.addTagPlaceholder', 'fr', 'Ajouter un tag...'),
  ('ui.addButton', 'fr', 'Ajouter'),
  ('ui.repeatEveryLabel', 'fr', 'Répéter tous les'),
  ('ui.frequencyLabel', 'fr', 'Fréquence'),
  ('ui.dayUnit', 'fr', 'Jour(s)'),
  ('ui.weekUnit', 'fr', 'Semaine(s)'),
  ('ui.monthUnit', 'fr', 'Mois'),
  ('ui.recurringLabel', 'fr', 'Récurrent'),
  ('ui.createTaskButton', 'fr', 'Créer la tâche'),
  ('ui.deleteTaskButton', 'fr', 'Supprimer'),
  ('ui.manageTagsTitle', 'fr', 'Gérer les tags'),
  ('ui.manageTagsSubtitle', 'fr', 'Organisez votre espace de travail'),
  ('ui.createNewTagPlaceholder', 'fr', 'Créer un nouveau tag...'),
  ('ui.createButton', 'fr', 'Créer'),
  ('ui.noTagsYet', 'fr', 'Aucun tag créé pour le moment.'),
  ('ui.editTagTitle', 'fr', 'Modifier le tag'),
  ('ui.deleteTagTitle', 'fr', 'Supprimer le tag'),
  ('ui.loadingProjectDetails', 'fr', 'Chargement des détails du projet...'),
  ('ui.loadingTags', 'fr', 'Chargement des tags...'),
  ('ui.taskTitleRequired', 'fr', 'Le titre est obligatoire'),
  ('ui.dueDateRequiredForRecurring', 'fr', 'La date d''échéance est obligatoire pour les tâches récurrentes'),
  ('ui.projectNameRequired', 'fr', 'Le nom du projet est obligatoire')
on conflict (key, language_code) do update set value = excluded.value;

-- de translations
insert into config_translations (key, language_code, value) values
  ('ui.noDueDate', 'de', 'Kein Fälligkeitsdatum'),
  ('ui.recurringTemplate', 'de', 'Wiederkehrende Vorlage'),
  ('ui.everyMonth', 'de', 'Alle 1 Monat'),
  ('ui.occurrences', 'de', 'Vorkommen'),
  ('ui.createProjectTitle', 'de', 'Neues Projekt erstellen'),
  ('ui.createProjectSubtitle', 'de', 'Etwas Neues beginnen'),
  ('ui.projectNameLabel', 'de', 'Projektname'),
  ('ui.projectNamePlaceholder', 'de', 'z.B. Persönliche Webseite'),
  ('ui.projectDescriptionLabel', 'de', 'Beschreibung'),
  ('ui.projectDescriptionPlaceholder', 'de', 'Worum geht es in diesem Projekt?'),
  ('ui.createProjectButton', 'de', 'Projekt erstellen'),
  ('ui.editProjectTitle', 'de', 'Projekt bearbeiten'),
  ('ui.editProjectSubtitle', 'de', 'Arbeitsbereich-Einstellungen'),
  ('ui.saveChangesButton', 'de', 'Änderungen speichern'),
  ('ui.deleteProjectButton', 'de', 'Löschen'),
  ('ui.deleteProjectConfirm', 'de', 'Sind Sie sicher, dass Sie dieses Projekt löschen möchten? Alle darin enthaltenen Aufgaben gehen verloren.'),
  ('ui.createTaskTitle', 'de', 'Aufgabe erstellen'),
  ('ui.editTaskTitle', 'de', 'Aufgabe bearbeiten'),
  ('ui.taskTitleLabel', 'de', 'Titel'),
  ('ui.taskTitlePlaceholder', 'de', 'Aufgabentitel'),
  ('ui.taskDescriptionLabel', 'de', 'Beschreibung'),
  ('ui.taskDescriptionPlaceholder', 'de', 'Beschreibung hinzufügen...'),
  ('ui.dueDateLabel', 'de', 'Fälligkeitsdatum'),
  ('ui.tagsLabel', 'de', 'Tags'),
  ('ui.addTagPlaceholder', 'de', 'Tag hinzufügen...'),
  ('ui.addButton', 'de', 'Hinzufügen'),
  ('ui.repeatEveryLabel', 'de', 'Wiederholen alle'),
  ('ui.frequencyLabel', 'de', 'Häufigkeit'),
  ('ui.dayUnit', 'de', 'Tag(e)'),
  ('ui.weekUnit', 'de', 'Woche(n)'),
  ('ui.monthUnit', 'de', 'Monat(e)'),
  ('ui.recurringLabel', 'de', 'Wiederkehrend'),
  ('ui.createTaskButton', 'de', 'Aufgabe erstellen'),
  ('ui.deleteTaskButton', 'de', 'Löschen'),
  ('ui.manageTagsTitle', 'de', 'Tags verwalten'),
  ('ui.manageTagsSubtitle', 'de', 'Organisieren Sie Ihren Arbeitsbereich'),
  ('ui.createNewTagPlaceholder', 'de', 'Neuen Tag erstellen...'),
  ('ui.createButton', 'de', 'Erstellen'),
  ('ui.noTagsYet', 'de', 'Noch keine Tags erstellt.'),
  ('ui.editTagTitle', 'de', 'Tag bearbeiten'),
  ('ui.deleteTagTitle', 'de', 'Tag löschen'),
  ('ui.loadingProjectDetails', 'de', 'Projektdetails werden geladen...'),
  ('ui.loadingTags', 'de', 'Tags werden geladen...'),
  ('ui.taskTitleRequired', 'de', 'Titel ist erforderlich'),
  ('ui.dueDateRequiredForRecurring', 'de', 'Fälligkeitsdatum ist für wiederkehrende Aufgaben erforderlich'),
  ('ui.projectNameRequired', 'de', 'Projektname ist erforderlich')
on conflict (key, language_code) do update set value = excluded.value;
